Repository Prasundas99/Web-Development-Traning, pull requests merged in 2022-10, with the labels that each got.

#93 Digital Clock
  04.JavaScript/Digital-Clock/app.js
  04.JavaScript/Digital-Clock/index.html
  04.JavaScript/Digital-Clock/style.css
Labels: hacktober-accept

#94 Light Bulb using JavaScript
  04.JavaScript/Light Bulb/app.js
  04.JavaScript/Light Bulb/index.html
  04.JavaScript/Light Bulb/style.css
Labels: hacktober-accept

#96 PHP Database Repository is updated with MySQLi and PDO connect.
  07.PHP/3.Databse/MySQLiconnect.php
  07.PHP/3.Databse/PDO.php
Labels: hacktober-accept

#120 Header updated with Date and Time, CSS of Header and Footer updated
  08.PHP mysql Project/css/add.css
  08.PHP mysql Project/css/footer.css
  08.PHP mysql Project/css/header.css
  08.PHP mysql Project/templates/footer.php
  08.PHP mysql Project/templates/header.php
Labels: enhancement, hacktober-accept

#136 Added audio visualizer project
  04.JavaScript/micaudiovisualizer/index.html
  04.JavaScript/micaudiovisualizer/readme.md
  04.JavaScript/micaudiovisualizer/script.js
  04.JavaScript/micaudiovisualizer/style.css
Labels: frontend, feature

#128 Added all basic HTML tags.
  01.HTML/3.HTML_tags.html
  01.HTML/README.md
Labels: enhancement, frontend
